### ISSUE TITLE
AnnotationTool segmentation fault on Create Trainingset (Ubuntu 20.04)

### ISSUE THREAD

**Issue by timsainb** [JARVIS-MoCap/JARVIS-AnnotationTool#10]
I am running through the tutorial and get a segmentation fault core dumped error when I click Create in the trainingset section. I had the same error on two different machines. 

I'm trying to build from source to see if I get the same error currently.

**Comment by timsainb** [comment]
I ended up updating to ubuntu to 22.04 and using that version of the software instead

**Comment by JARVIS-MoCap** [comment]
Thanks for reporting this issue! 
Unfortunately I am not able to reproduce the segmentation fault using a dataset I created following the tutorial. Would you mind sharing the dataset that causes the segfaults for you with me? 
Apart from that you could also try reinstalling the latest version of the AnnotationTool from [here](https://github.com/JARVIS-MoCap/JARVIS-AnnotationTool/releases/tag/v1.2), maybe it is related to the problems caused by the OpenCV install mentioned in  #11 

Hope this helps,
Timo

**Comment by timsainb** [comment]
The new version resolved this issue. Thanks!
