### ISSUE TITLE
Callibration Unsuccessful in tutorial

### ISSUE THREAD

**Issue by timsainb** [JARVIS-MoCap/JARVIS-AnnotationTool#11]
I get this error, even though the callibration appears to find the checkerboard. Any idea why? 

`Calibration unsuccessful! Camera Camera_RBB: Found only 1 valid checkerboards, aborting calibration. Make sure your checkerboard parameters are set correctly.`

Here is the debugging image. No debugging images are saved for extrinsic calibration (is that the issue here?)

![Frame_0](https://user-images.githubusercontent.com/1279238/190441463-7be08e71-8237-413f-ae89-7cddcf62b846.jpg)

**Comment by JARVIS-MoCap** [comment]
Thanks for reporting this issue! 

I looked into it and it seems like it was caused by a bad configuration of OpenCV in the Ubuntu 20.04 Debian package. It was configured to use the GStreamer instead of the FFMPEG backend, causing compatibility issues with the encoding of the example videos. 
I reuploaded a fixed version of the debian package [here](https://github.com/JARVIS-MoCap/JARVIS-AnnotationTool/releases/tag/v1.2) to reinstall it first run 

     sudo dpkg -r AnnotationTool

And then install the new version by running

     sudo apt install ./JARVIS-AnnotationTool_1.2-1_amd64_2004.deb 

Please let me know if the issue persists with the new version.

Best,
Timo

**Comment by timsainb** [comment]
This worked, thanks Timo!
