### ISSUE TITLE
AnnotationTool crashes when using trackpad with mac app

### ISSUE THREAD

**Issue by timsainb** [JARVIS-MoCap/JARVIS-AnnotationTool#14]
I'm using V1.2, off the shelf, on osx monterey. I haven't tried compiling myself. 

When I trey to do annotations with a mac using my trackpad to scross in the annotation window, I get the following error: 

```
/AnnotationTool
2022-10-04T13:43:03: [W] Populating font family aliases took 153 ms. Replace uses of missing font family "Sans Serif" with one that exists to avoid this cost.  (unknown - unknown:0)
[1]    2775 floating point exception  ./AnnotationTool
```

The same issue does not occur with a mouse/scrolls wheel.

**Comment by JARVIS-MoCap** [comment]
I don't have a MacBook with a trackpad to test this unfortunately, but my buest guess to what is causing this issue is that the trackpad can generate mouse-scroll events with a angle-delta of 0, causing a zero division error. I modified the scrolling function to filter out events with 0 scrolling angle and updated the MacOS version in the 1.2 release. It would be great if you could check if that fixes the issue! :)
